---
_extends: template

repository:
  name: hs-toxcore-c
  description: Haskell bindings to C toxcore implementation
  topics: toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - WIP
          - code-review/reviewable
          - coverage/coveralls
          - license/cla
