---
_extends: .github

repository:
  name: hs-toxcore-c
  description: Haskell bindings to C toxcore implementation
  topics: toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "bazel-opt"
          - "build / stack"
