---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.23-third_party
    cpu: 2
    memory: 6G
  configure_script:
    - /src/workspace/tools/inject-repo hs-toxcore-c
  test_all_script:
    - cd /src/workspace && bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --config=release
        //hs-toxcore-c/...
