language: haskell
ghc: 7.8

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:
  # Where to find libraries.
  - export LD_LIBRARY_PATH=$HOME/.ghc/usr/lib
  - export PKG_CONFIG_PATH=$HOME/.ghc/usr/lib/pkgconfig
  # c-sodium
  - git clone --depth=1 --branch=stable https://github.com/jedisct1/libsodium
  - (cd libsodium && ./configure --prefix=$HOME/.ghc/usr && make install -j$(nproc))
  # c-toxcore
  - git clone --depth=1 https://github.com/TokTok/toxcore
  - (cd toxcore && cmake -B_build -H. -DCMAKE_INSTALL_PREFIX:PATH=$HOME/.ghc/usr && make -C_build install -j$(nproc))
  - cabal install --only-dependencies --enable-tests --extra-include-dirs=$HOME/.ghc/usr/include --extra-lib-dirs=$HOME/.ghc/usr/lib
